spring:
  config:
    name: kpSpringServer
  datasource:
    url: jdbc:postgresql://localhost:5432/kpdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  servlet:
    session:
      timeout: 5m
