on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - studyServer
jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Run Detekt
        run: ./gradlew detekt




name: base checks
