on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - studyServer
jobs:
  spotbugs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: oracle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run SpotBugs
        run: ./gradlew spotbugsMain




name: base checks
