on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - studyServer
jobs:
  checkcode:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Check kotlin Versions
        uses: fwilhe2/setup-kotlin@main

      - name: Install dependencies
        run: |
          ./gradlew dependencies

      - name: Run Detekt
        run: ./gradlew detekt



name: base checks
